---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

os: "linux"
dist: "xenial"
language: "python"

services:
- "docker"

install:
# Install dependencies
- "pip install ansible ansible-lint yamllint molecule molecule-docker"

# Make sure the role is found
- "pushd .."
- "ln -s ansible-role-skel mireiawen.skel"
- "popd"

# Print versions before running
before_script:
- "ansible --version"
- "ansible-lint --version"
- "yamllint --version"
- "molecule --version"

stages:
- "test"

jobs:
  include:

  # Default test
  - stage: "test"
    name: "Alpine"
    script:
    - "molecule test"

notifications:
  webhooks: "https://galaxy.ansible.com/api/v1/notifications/"
