---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: "Set the system name"
  template:
    src: "system_name.j2"
    dest: "/etc/system_name"

- name: "Make sure skel exists"
  file:
    name: "/etc/skel"
    state: "directory"

- name: "Configure the skel"
  include_tasks: "skel-file.yml"
  vars:
    filename: "{{ item }}"
    dest: "/etc/skel"
  with_items:
  - "bashrc"
  - "bash_logout"
  - "profile"
  - "vimrc"

- name: "Configure root"
  include_tasks: "skel-file.yml"
  vars:
    filename: "{{ item }}"
    dest: "/root"
  with_items:
  - "bashrc"
  - "bash_logout"
  - "profile"
  - "vimrc"
